import type { Product, ProductCategoryFilter } from "../../types/products/types";

export const productCategories: ProductCategoryFilter[] = [
  "ทั้งหมด",
  "Flagship",
  "Mid-Range",
  "Budget",
];

export const products: Product[] = [
  {
    id: 1,
    name: "iPhone 15 Pro Max",
    brand: "Apple",
    model: "A3293",
    sku: "APL-IP15PM-256",
    category: "Flagship",
    price: 1199,
    cost: 980,
    stock: 12,
  },
  {
    id: 2,
    name: "Google Pixel 8 Pro",
    brand: "Google",
    model: "GP4BC",
    sku: "GGL-P8P-128",
    category: "Flagship",
    price: 999,
    cost: 780,
    stock: 12,
  },
  {
    id: 3,
    name: "OnePlus 12",
    brand: "OnePlus",
    model: "CPH2581",
    sku: "OP-12-256",
    category: "Mid-Range",
    price: 999,
    cost: 780,
    stock: 12,
  },
  {
    id: 4,
    name: "Realme GT6",
    brand: "Realme",
    model: "RMX3851",
    sku: "RLM-GT6-256",
    category: "Budget",
    price: 349,
    cost: 260,
    stock: 12,
  },
  {
    id: 5,
    name: "OnePlus 12",
    brand: "OnePlus",
    model: "CPH2581",
    sku: "OP-12-256",
    category: "Mid-Range",
    price: 999,
    cost: 780,
    stock: 12,
  },
  {
    id: 6,
    name: "iPhone 15 Pro Max",
    brand: "Apple",
    model: "A3293",
    sku: "APL-IP15PM-256",
    category: "Flagship",
    price: 1199,
    cost: 980,
    stock: 12,
  },
  {
    id: 7,
    name: "Google Pixel 8 Pro",
    brand: "Google",
    model: "GP4BC",
    sku: "GGL-P8P-128",
    category: "Flagship",
    price: 999,
    cost: 780,
    stock: 12,
  },
  {
    id: 8,
    name: "Realme GT6",
    brand: "Realme",
    model: "RMX3851",
    sku: "RLM-GT6-256",
    category: "Budget",
    price: 349,
    cost: 260,
    stock: 12,
  },
];
